name: ci

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add release date to index.html
        run: |
          VERSION="$(date +'%Y-%m-%d %H:%M')"
          sed --in-place "s/<VERSION>/$VERSION/g" index.html
        shell: bash

      - name: Setup emscripten SDK
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: '1.38.45'

      - name: Verify emscripten
        run: emcc -v

      - name: Setup Stable Rust with emscripten target
        run: rustup target add wasm32-unknown-emscripten

      - name: Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Cargo clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Cargo fmt
        run: cargo fmt --all --check

      - name: Cargo test
        run: cargo test

      - name: Build site into the public/ dir
        run: ./script/build.sh

      - uses: actions/upload-pages-artifact@v3
        if: ${{ github.event_name != 'pull_request' }}
        with:
          path: './public'
          retention-days: '1'

  deploy:
    # Separate step to keep the permissions separated.
    needs: build
    if: ${{ github.event_name != 'pull_request' }}
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
